/**
 * Domain vocabulary shared by the public site, the CMS, and the AI engine.
 * These string unions mirror the Postgres enums in supabase/migrations.
 */

export const PILLARS = ["vibes", "suara", "hustle", "story"] as const;
export type Pillar = (typeof PILLARS)[number];

export const ARTICLE_STATUSES = [
  "draft",
  "needs_review",
  "scheduled",
  "published",
  "archived",
] as const;
export type ArticleStatus = (typeof ARTICLE_STATUSES)[number];

export const USER_ROLES = [
  "reader",
  "analyst",
  "contributor",
  "writer",
  "media_manager",
  "editor",
  "commercial_manager",
  "managing_editor",
  "owner",
] as const;
export type UserRole = (typeof USER_ROLES)[number];

export const REACTION_TYPES = ["like", "save", "share"] as const;
export type ReactionType = (typeof REACTION_TYPES)[number];

export const CONTRIBUTION_STATUSES = [
  "pending",
  "approved",
  "rejected",
] as const;
export type ContributionStatus = (typeof CONTRIBUTION_STATUSES)[number];

export const IMAGE_SOURCES = [
  "upload",
  "unsplash",
  "pexels",
  "pixabay",
] as const;
export type ImageSource = (typeof IMAGE_SOURCES)[number];

/**
 * What a visual *is*, as opposed to where the file came from.
 *
 * `ImageSource` above records the upload origin (a Cloudinary upload, a Pexels
 * result). This records the editorial status of the frame, which is the thing a
 * reader needs to know: whether they are looking at evidence, an illustration,
 * or a development placeholder.
 */
export const MEDIA_SOURCE_TYPES = [
  /** Photographed by us or a named contributor at the place described. */
  "original_photo",
  /** Stock or wire photo under licence, credited to its photographer. */
  "licensed_photo",
  /** Sent in by a reader, with consent recorded. */
  "community_submission",
  /** Map, chart, diagram, or other authored graphic. */
  "editorial_graphic",
  /** Generated by a model. Never evidence of anything. */
  "ai_illustration",
  /** Development placeholder. Must never reach production. */
  "mock_visual",
] as const;
export type MediaSourceType = (typeof MEDIA_SOURCE_TYPES)[number];

/**
 * Provenance travels with every visual. The three booleans exist so a template
 * never has to infer intent from the credit string: a caption generator, an
 * indexer, or a reviewer can ask directly whether a frame claims to show a real
 * place or a real event.
 */
export interface MediaProvenance {
  sourceType: MediaSourceType;
  /** Shown to readers. Must not claim reporting that did not happen. */
  credit: string;
  /** True when the frame illustrates an idea rather than documenting a fact. */
  isIllustrative: boolean;
  depictsActualLocation: boolean;
  depictsActualEvent: boolean;
  /** Reader-facing sentence, rendered under the image when present. */
  disclosure: string | null;
}

export function isMediaSourceType(value: unknown): value is MediaSourceType {
  return (
    typeof value === "string" &&
    (MEDIA_SOURCE_TYPES as readonly string[]).includes(value)
  );
}

export const AI_KEY_STATUSES = [
  "active",
  "rate_limited",
  "error",
  "disabled",
] as const;
export type AiKeyStatus = (typeof AI_KEY_STATUSES)[number];

export const AI_TASK_TYPES = [
  "brand",
  "ideation",
  "headline",
  "outline",
  "draft",
  "rewrite",
  "seo",
  "image",
  "quality",
  "social",
  "copilot",
  "connection_test",
] as const;
export type AiTaskType = (typeof AI_TASK_TYPES)[number];

export const AI_JOB_STATUSES = [
  "pending",
  "processing",
  "completed",
  "failed",
] as const;
export type AiJobStatus = (typeof AI_JOB_STATUSES)[number];

export const REWRITE_JOB_STATUSES = [
  "pending",
  "processing",
  "needs_review",
  "completed",
  "failed",
] as const;
export type RewriteJobStatus = (typeof REWRITE_JOB_STATUSES)[number];

export const DIRECTORY_TYPES = ["loker", "umkm", "kos", "event"] as const;
export type DirectoryType = (typeof DIRECTORY_TYPES)[number];

export interface PillarMeta {
  readonly slug: Pillar;
  readonly label: string;
  readonly wordmark: string;
  readonly tagline: string;
  readonly description: string;
  /** Banner ink for this pillar. Tailwind class fragments live in the UI. */
  readonly ink: "lime" | "orange" | "bone" | "wall";
}

export const PILLAR_META: Record<Pillar, PillarMeta> = {
  vibes: {
    slug: "vibes",
    label: "Vibes",
    wordmark: "TNG VIBES",
    tagline: "Nongkrong, kuliner, event, kultur",
    description:
      "Tempat makan yang beneran enak, spot nongkrong yang masih sepi, dan event yang layak diantre. Ditulis oleh orang yang ikut antre.",
    ink: "lime",
  },
  suara: {
    slug: "suara",
    label: "Suara",
    wordmark: "SUARA TANGERANG",
    tagline: "Isu kota, transportasi, ruang publik",
    description:
      "Macet, angkot, trotoar, sewa, kebijakan. Isu yang kena ke hidup kamu tiap hari, dijelaskan tanpa bahasa rilis pers.",
    ink: "orange",
  },
  hustle: {
    slug: "hustle",
    label: "Hustle",
    wordmark: "TNG HUSTLE",
    tagline: "Loker, UMKM, side hustle, biaya hidup",
    description:
      "Loker yang syaratnya jelas, UMKM yang bisa dicontek, dan angka biaya hidup yang tidak dikarang.",
    ink: "bone",
  },
  story: {
    slug: "story",
    label: "Story",
    wordmark: "TNG STORY",
    tagline: "Cerita orang, komunitas, kreator",
    description:
      "Cerita warga Tangerang yang tidak masuk headline. Panjang, personal, dan tidak dibuat drama.",
    ink: "wall",
  },
};

export function isPillar(value: unknown): value is Pillar {
  return typeof value === "string" && (PILLARS as readonly string[]).includes(value);
}

export function isArticleStatus(value: unknown): value is ArticleStatus {
  return (
    typeof value === "string" &&
    (ARTICLE_STATUSES as readonly string[]).includes(value)
  );
}

export function isUserRole(value: unknown): value is UserRole {
  return (
    typeof value === "string" && (USER_ROLES as readonly string[]).includes(value)
  );
}

/** Role ranking used by `requireRole`. Higher wins. */
export const ROLE_RANK: Record<UserRole, number> = {
  reader: 0,
  analyst: 10,
  contributor: 20,
  writer: 30,
  media_manager: 40,
  editor: 50,
  commercial_manager: 50,
  managing_editor: 70,
  owner: 100,
};

export function roleAtLeast(role: UserRole, minimum: UserRole): boolean {
  return ROLE_RANK[role] >= ROLE_RANK[minimum];
}

export function highestUserRole(values: readonly unknown[]): UserRole {
  return values.reduce<UserRole>((highest, value) => {
    if (!isUserRole(value)) return highest;
    return roleAtLeast(value, highest) ? value : highest;
  }, "reader");
}
